// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['app']['App']['BrowserOpenURL'](arg1);
}

export function CheckConnection() {
  return window['go']['app']['App']['CheckConnection']();
}

export function IsBackendReady() {
  return window['go']['app']['App']['IsBackendReady']();
}
