// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1:string):Promise<void>;

export function CheckConnection():Promise<string>;

export function IsBackendReady():Promise<boolean>;
