// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function IsBackendReady() {
  return window['go']['main']['App']['IsBackendReady']();
}
